/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface OffersList {}
  interface OffersListAttributes extends StencilHTMLAttributes {}

  interface SearchBox {}
  interface SearchBoxAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'OffersList': Components.OffersList;
    'SearchBox': Components.SearchBox;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'offers-list': Components.OffersListAttributes;
    'search-box': Components.SearchBoxAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLOffersListElement extends Components.OffersList, HTMLStencilElement {}
  var HTMLOffersListElement: {
    prototype: HTMLOffersListElement;
    new (): HTMLOffersListElement;
  };

  interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {}
  var HTMLSearchBoxElement: {
    prototype: HTMLSearchBoxElement;
    new (): HTMLSearchBoxElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'offers-list': HTMLOffersListElement
    'search-box': HTMLSearchBoxElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'offers-list': HTMLOffersListElement;
    'search-box': HTMLSearchBoxElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
